// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxPrrnrswpFjUlH00YazmbT4_VdKf8OU',
    appId: '1:211773176462:web:39e5f4ad6a80b0655227df',
    messagingSenderId: '211773176462',
    projectId: 'turkticaretnetcase',
    authDomain: 'turkticaretnetcase.firebaseapp.com',
    storageBucket: 'turkticaretnetcase.appspot.com',
    measurementId: 'G-ML0C5R6VJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBQpJMB0NLelVCX4yfikIN-axK6JX7-k',
    appId: '1:211773176462:android:f6349943f8450e2d5227df',
    messagingSenderId: '211773176462',
    projectId: 'turkticaretnetcase',
    storageBucket: 'turkticaretnetcase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MXwexJkfzWcfjXOSPKKJHweuu2HDZC8',
    appId: '1:211773176462:ios:93104327acbea5125227df',
    messagingSenderId: '211773176462',
    projectId: 'turkticaretnetcase',
    storageBucket: 'turkticaretnetcase.appspot.com',
    iosClientId: '211773176462-j7nceklngmgl4jlmh7on2s7nut9lsrae.apps.googleusercontent.com',
    iosBundleId: 'com.example.turkticaretnetcase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MXwexJkfzWcfjXOSPKKJHweuu2HDZC8',
    appId: '1:211773176462:ios:93104327acbea5125227df',
    messagingSenderId: '211773176462',
    projectId: 'turkticaretnetcase',
    storageBucket: 'turkticaretnetcase.appspot.com',
    iosClientId: '211773176462-j7nceklngmgl4jlmh7on2s7nut9lsrae.apps.googleusercontent.com',
    iosBundleId: 'com.example.turkticaretnetcase',
  );
}
